mobile_robot:
  # publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers
  joint_hook_controller:
    type: effort_controllers/JointPositionController
    joint: joint_support_hook
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_horizontal_controller:
    type: effort_controllers/JointPositionController
    joint: joint_slider_slider
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_vertical_controller:
    type: effort_controllers/JointPositionController
    joint: joint_bar_vslider
    pid: {p: 1000.0, i: 0.01, d: 10.0}
